pipeline {
    agent none
    stages {
        stage('Back-end') {
	  agent {
           docker { image 'maven:3.8.1-adoptopenjdk-11' }
          }
           steps {
              script {
                    // Define the Java code in a separate file
                    writeFile file: 'HelloWorld.java', text: '''
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
                    '''
                    
                    // Compile and run the Java code
                    sh 'javac HelloWorld.java'
                    sh 'java HelloWorld'
                }
            }
        }
        stage('Front-end') {
	 agent {
           docker { image 'node:16-alpine' }
         }
         steps {
                // Run the Node.js code
                sh 'node -e "console.log(\\"Hello, World!\\");"'
            }
        }
    }
}
